wip

diff --git a/bionemo b/bionemo
--- a/bionemo
+++ b/bionemo
@@ -49,10 +49,10 @@ LOCAL_ENV=.env
 if [ -e ./$LOCAL_ENV ]
 then
     echo "Sourcing environment from ./$LOCAL_ENV"
-    . ./$LOCAL_ENV
+    source ./$LOCAL_ENV
     write_env=0
 else
-    echo "$LOCAL_ENV does not exist. Writing deafults to $LOCAL_ENV"
+    echo "$LOCAL_ENV does not exist. Writing defaults to $LOCAL_ENV"
     write_env=1
 fi
 
@@ -126,6 +126,27 @@ build() {
 }
 
 dev() {
+
+  set +u
+  local CMD
+  if [[ "$2" != "" ]]; then
+    CMD="$2"
+  else
+    echo "Using bash as the default command. Override with 2nd argument value to in-image executable."
+    CMD="bash"
+  fi
+  set -u
+
+  # ensure that we have the image present
+  set +e
+  docker pull "${IMAGE_REPO}:${IMAGE_TAG}"
+  if [[ "$?" != "0" ]]; then
+    echo "ERROR: must build the image before launching a container!"
+    echo "ERROR: could not obtain '${IMAGE_REPO}:${IMAGE_TAG}'"
+    exit 1
+  fi
+  set -e
+
   # Compare Docker version to find Nvidia Container Toolkit support.
   # Please refer https://github.com/NVIDIA/nvidia-docker
   local DOCKER_VERSION=$(docker version | grep -i version | head -1 | awk '{print $2}')
@@ -138,14 +159,6 @@ dev() {
   fi
 
   echo "Mounting ~/.ssh, /etc/{passwd,group,shadow} for development"
-
-
-  # We used to start the container as non-root
-  # -u $(id -u):$(id -g) \
-  # but this runs into problems because everything that is installed in the image is owned by root.
-  # So doing this means that
-
-
   local DOCKER_CMD="docker run \
     --network host \
     ${PARAM_RUNTIME} \
@@ -169,15 +182,7 @@ dev() {
     -e HOME=/workspace/bionemo2 -w /workspace/bionemo2 \
     -v ${HOME}/.ssh:/workspace/bionemo2/.ssh:ro"
 
-    set +u
-    local CMD
-    if [[ "$2" != "" ]]; then
-      CMD="$2"
-    else
-      echo "Using bash as the default command. Override with 2nd argument value to in-image executable."
-      CMD="bash"
-    fi
-    set -u
+
 
     set -x
     ${DOCKER_CMD} --name "${DEV_CONT_NAME}" --rm -it "${IMAGE_REPO}:${IMAGE_TAG}" ${CMD}
