should be working

diff --git a/bionemo b/bionemo
--- a/bionemo
+++ b/bionemo
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
 
-#Name of the Docker image
 IMAGE_NAME=${IMAGE_NAME:=nvcr.io/nvidian/cvai_bnmo_trng/bionemo}
 COMMIT=$(git rev-parse HEAD)
 IMAGE_TAG="bionemo2-${COMMIT}"
 CACHE_TAG="bionemo2-latest"
 
-# Defaults for `.env` file
 export LOCAL_REPO_PATH
 LOCAL_REPO_PATH=$(realpath -s "$(pwd)")
 export DOCKER_REPO_PATH=${DOCKER_REPO_PATH:=/workspace/bionemo2}
@@ -25,26 +23,6 @@ export NGC_CLI_API_KEY=${NGC_CLI_API_KEY:=NotSpecified}
 export NGC_CLI_ORG=${NGC_CLI_ORG:=nvidian}
 export NGC_CLI_TEAM=${NGC_CLI_TEAM:=NotSpecified}
 export NGC_CLI_FORMAT_TYPE=${NGC_CLI_FORMAT_TYPE:=ascii}
-
-# Default paths for framework. We switch these depending on whether or not we are inside
-# a docker environment. It is assumed that if we are in a docker environment, then it's the
-# bionemo image built with `Dockerfile`.
-
-# TODO: deleteme
-#if [ -f /.dockerenv ]; then
-#    echo "Running inside a Docker container, using DOCKER paths from .env file."
-#    RESULT_PATH=${DOCKER_RESULTS_PATH}
-#    DATA_PATH=${DOCKER_DATA_PATH}
-#    MODEL_PATH=${DOCKER_MODELS_PATH}
-#    BIONEMO_HOME=${DOCKER_REPO_PATH}
-#else
-#    echo "Not running inside a Docker container, using LOCAL paths from .env file."
-#    RESULT_PATH=${LOCAL_RESULTS_PATH}
-#    DATA_PATH=${LOCAL_DATA_PATH}
-#    MODEL_PATH=${LOCAL_MODELS_PATH}
-#    BIONEMO_HOME=${LOCAL_REPO_PATH}
-#fi
-
 
 #Function to build the Docker image
 build() {
@@ -79,13 +57,17 @@ build() {
     local DOCKER_BUILD_CMD="docker buildx build \
         -t ${IMAGE_NAME}:${IMAGE_TAG} \
         --cache-to type=inline \
-	    --cache-from ${IMAGE_NAME}:${CACHE_TAG} \
+	      --cache-from ${IMAGE_NAME}:${CACHE_TAG} \
         --label com.nvidia.bionemo.git_sha=${COMMIT} \
         --label com.nvidia.bionemo.created_at=${created_at} \
         -f ./Dockerfile"
     echo "$DOCKER_BUILD_CMD"
-    $DOCKER_BUILD_CMD .
-    echo "Docker build completed successfully."
+    DOCKER_BUILDKIT=1 $DOCKER_BUILD_CMD .
+    if [[ "$?" == "0" ]]; then
+      echo "Docker build completed successfully."
+    else
+      echo "FAILURE: image was not built. Check logs for error."
+    fi
 }
 
 dev() {
@@ -107,6 +89,7 @@ dev() {
       PARAM_RUNTIME="--runtime=nvidia"
   fi
 
+  echo "Mounting ~/.ssh, /etc/{passwd,group,shadow} for development"
 
   local DOCKER_CMD
   DOCKER_CMD="docker run \
@@ -115,43 +98,36 @@ dev() {
     -p ${JUPYTER_PORT}:8888 \
     --shm-size=4g \
     -e TMPDIR=/tmp/ \
-    -e NUMBA_CACHE_DIR=/tmp/ "
-
-    # Note: For BIONEMO_HOME, if we are invoking docker, this should always be
-    # the docker repo path.
-    DOCKER_CMD="${DOCKER_CMD} --env BIONEMO_HOME=$DOCKER_REPO_PATH"
-    DOCKER_CMD="${DOCKER_CMD} --env WANDB_API_KEY=$WANDB_API_KEY"
-    DOCKER_CMD="${DOCKER_CMD} --env NGC_CLI_API_KEY=$NGC_CLI_API_KEY"
-    DOCKER_CMD="${DOCKER_CMD} --env NGC_CLI_ORG=$NGC_CLI_ORG"
-    DOCKER_CMD="${DOCKER_CMD} --env NGC_CLI_TEAM=$NGC_CLI_TEAM"
-    DOCKER_CMD="${DOCKER_CMD} --env NGC_CLI_FORMAT_TYPE=$NGC_CLI_FORMAT_TYPE"
-
-    # For development work
-    DOCKER_CMD="${DOCKER_CMD} -v $LOCAL_REPO_PATH:$DOCKER_REPO_PATH"
-    DOCKER_CMD="${DOCKER_CMD} -v ${LOCAL_RESULTS_PATH}:${DOCKER_RESULTS_PATH}"
-    DOCKER_CMD="${DOCKER_CMD} -v ${LOCAL_DATA_PATH}:${DOCKER_DATA_PATH}"
-    DOCKER_CMD="${DOCKER_CMD} -v ${LOCAL_MODELS_PATH}:${DOCKER_MODELS_PATH}"
-    DOCKER_CMD="${DOCKER_CMD} -v /etc/passwd:/etc/passwd:ro "
-    DOCKER_CMD="${DOCKER_CMD} -v /etc/group:/etc/group:ro "
-    DOCKER_CMD="${DOCKER_CMD} -v /etc/shadow:/etc/shadow:ro "
-    DOCKER_CMD="${DOCKER_CMD} -u $(id -u):$(id -g) "
-    DOCKER_CMD="${DOCKER_CMD} -e HOME=/workspace/bionemo2 -w /workspace/bionemo2 "
-
-    # For dev mode, mount the local code for development purpose
-    # and mount .ssh dir for working with git
-    if [[ $1 == "dev" ]]; then
-        echo "Mounting ~/.ssh up for development"
-        DOCKER_CMD="$DOCKER_CMD -v ${HOME}/.ssh:/workspace/bionemo2/.ssh:ro"
-    fi
+    -e NUMBA_CACHE_DIR=/tmp/ \
+    -e BIONEMO_HOME=$DOCKER_REPO_PATH \
+    -e WANDB_API_KEY=$WANDB_API_KEY \
+    -e NGC_CLI_API_KEY=$NGC_CLI_API_KEY \
+    -e NGC_CLI_ORG=$NGC_CLI_ORG \
+    -e NGC_CLI_TEAM=$NGC_CLI_TEAM \
+    -e NGC_CLI_FORMAT_TYPE=$NGC_CLI_FORMAT_TYPE \
+    -v $LOCAL_REPO_PATH:$DOCKER_REPO_PATH \
+    -v ${LOCAL_RESULTS_PATH}:${DOCKER_RESULTS_PATH} \
+    -v ${LOCAL_DATA_PATH}:${DOCKER_DATA_PATH} \
+    -v ${LOCAL_MODELS_PATH}:${DOCKER_MODELS_PATH} \
+    -v /etc/passwd:/etc/passwd:ro \
+    -v /etc/group:/etc/group:ro \
+    -v /etc/shadow:/etc/shadow:ro \
+    -u $(id -u):$(id -g) \
+    -e HOME=/workspace/bionemo2 -w /workspace/bionemo2 \
+    -v ${HOME}/.ssh:/workspace/bionemo2/.ssh:ro"
 
     local CMD
-    CMD="${CMD:-bash}"
+    if [[ "$2" != "" ]]; then
+      CMD="$2"
+    else
+      echo "Using bash as the default command. Override with 2nd argument value to exectuable."
+      CMD="bash"
+    fi
 
-    local IMAGE_TO_RUN
-    IMAGE_TO_RUN=$IMAGE_NAME:$IMAGE_TAG
+    local IMAGE_TO_RUN="${IMAGE_NAME}:${IMAGE_TAG}"
 
     set -x
-    ${DOCKER_CMD}  --name ${DEV_CONT_NAME}  --rm -it "${IMAGE_TO_RUN}" ${CMD}
+    ${DOCKER_CMD} --name "${DEV_CONT_NAME}" --rm -it "${IMAGE_TO_RUN}" ${CMD}
     set +x
     exit 0
 }
@@ -160,23 +136,11 @@ case "$1" in
     build)
         build
         ;;
-    run)
-        run
-        ;;
     dev)
         dev
         ;;
-    pull)
-        pull
-        ;;
-    update_build_cache)
-        update_build_cache
-        ;;
-    build_and_update_cache)
-        build_and_update_cache
-        ;;
     *)
-        echo "Usage: $0 {build|update_build_cache|build_and_update_cache|run|dev|pull}"
+        echo "Usage: $0 {build||dev [cmd]}"
         exit 1
         ;;
 esac
