changed ifs and added check status
Signed-off-by: dorotat <dorotat@nvidia.com>

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -161,14 +161,14 @@ jobs:
       credentials:
         username: ${{ vars.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
+    if: |
+      github.event_name == 'schedule' || github.event_name != 'merge_group' ||
+      contains(fromJSON(needs.get-pr-labels.outputs.labels || '[]'), 'INCLUDE_SLOW_TESTS')
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
       - name: Run slow tests
-        if: |
-          github.event_name == 'schedule' ||
-          contains(fromJSON(needs.get-pr-labels.outputs.labels || '[]'), 'INCLUDE_SLOW_TESTS')
         env:
           BIONEMO_DATA_SOURCE: ngc
         # Not every sub-package has slow tests, and since some sub-packages have tests under the same name we need
@@ -181,6 +181,9 @@ jobs:
       - build-bionemo-image
       - get-pr-labels
     runs-on: linux-amd64-gpu-l4-latest-1
+    if: |
+      github.event_name == 'schedule' || github.event_name != 'merge_group' ||
+      contains(fromJSON(needs.get-pr-labels.outputs.labels || '[]'), 'INCLUDE_NOTEBOOKS_TESTS')
     container:
       image: svcbionemo023/bionemo-framework:${{ github.run_id }}
       credentials:
@@ -191,9 +194,6 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Run notebook tests
-        if: |
-          github.event_name == 'schedule' ||
-          contains(fromJSON(needs.get-pr-labels.outputs.labels || '[]'), 'INCLUDE_NOTEBOOKS_TESTS')
         env:
           BIONEMO_DATA_SOURCE: ngc
           # this variable should be used in the notebooks to run a subset of the model layers or a smaller model/dataset
@@ -204,3 +204,23 @@ jobs:
           # Find and remove files not tracked by git in docs/ and sub-packages/
           git clean -fdx docs/ sub-packages/
           echo "Cleanup complete."
+
+  verify-tests-status:
+    name: Verify All Tests Status
+    needs: # List all your run-*-test jobs
+      - run-tests
+      - run-slow-tests
+      - run-notebooks-docs
+      # Add all other run-*-test jobs
+    runs-on: ubuntu-latest
+    if: always() # This ensures the job runs even if previous jobs fail
+    steps:
+      - name: Check test job statuses
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "Some test jobs have failed or been cancelled!"
+            exit 1
+          else
+            echo "All test jobs have completed successfully or been skipped!"
+            exit 0
+          fi
